### ISSUE TITLE
When i run the `new-endpoint` command the index function name is always updateMonitoring

### ISSUE THREAD

**Issue by alexBonadei** [mia-care/node.js-mia-care-template#8]
When I create a new endpoint via `npm run new-endpoint GET /hello-world getHelloWorld` the file index.js in the newly created folder exposes a funcion called `updateMonitoring`. It's probably a typo

**Comment by nicola88** [comment]
Fixed by https://github.com/mia-care/node.js-mia-care-template/pull/17
